### ISSUE TITLE
How to continuously integrate the theme with travis-ci?

### ISSUE THREAD

**Issue by tufu9441** [ahaasler/hexo-theme-colos#9]
I note that you have continuously integrated this theme with travis-ci, can you teach me how to do it? Because I am a completely new travis-ci user, especially don't know how to write the `.travis.yml` file. It will be very appreciated if you give me some guidance. Thanks!

**Comment by ahaasler** [comment]
I don't know what you mean with _"integrate this theme with travis-ci"_. I use Travis CI in this project to release the generated theme to the _master_ branch.

If you want to use this theme you must put it in the `themes` folder of your Hexo project and specify `colos` as theme in the Hexo configuration file.

But I think what you want is to deploy your site automatically to the _gh-pages_ branch of your repo instead of executing `hexo deploy` on your workspace. If that's the case I found [this great guide](https://sazzer.github.io/blog/2015/05/04/Deploying-Hexo-to-Github-Pages-with-Travis/) by @sazzer with a simple [search](http://lmgtfy.com/?q=hexo+travis+ci+deploy).

To learn about Travis CI and how to write a `.travis.yml` I recommend reading the [Travis CI docs](http://docs.travis-ci.com/user/getting-started/).

**Comment by tufu9441** [comment]
Thank you for reply, but I think you misunderstood me, I just want to trigger
Travis-ci each time I update a hexo theme repository in my github, because I am
also a theme maker, but I just don't know how to use Travis-ci to test,build and
pass my project. Thank you!

On 周二, 11月 3, 2015 at 06:30, ahaasler/hexo-theme-colos
reply@reply.github.com
wrote:
Closed #9 [https://github.com/ahaasler/hexo-theme-colos/issues/9] .

—
Reply to this email directly or view it on GitHub
[https://github.com/ahaasler/hexo-theme-colos/issues/9#event-452563022] .[https://github.com/notifications/beacon/AGec2anl3AEbQSUAz19X2hdV_r33NeYNks5pB9uVgaJpZM4GaKhF.gif]

**Comment by ahaasler** [comment]
Travis CI automatically triggers builds if a repo changes. You just have to log in and add the repository (it's integrated with GitHub).

If you want to trigger a build on a repo if another one changes you can use the [Travis CI API](http://docs.travis-ci.com/user/triggering-builds/) on the one that changes.
